export const FETCH_AUTH = 'FETCH_AUTH';
export const ERROR_AUTH = 'ERROR_AUTH';

export const LOADING_AUTH = 'LOADING_AUTH';
export const LOADING_EXPENSE = 'LOADING_EXPENSE';
export const LOADING_CATEGORY = 'LOADING_CATEGORY';

export const FETCH_EXPENSES = 'FETCH_EXPENSES';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ERROR_EXPENSE = 'ERROR_EXPENSE';
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const IS_EDIT_EXPENSE = 'IS_EDIT_EXPENSE';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const ERROR_CATEGORY = 'ERROR_CATEGORY';

export const FETCH_CAROUSEL = 'FETCH_CAROUSEL';

export const OPEN_ADD_EXPENSE_MODEL = 'OPEN_ADD_EXPENSE_MODEL';
export const CLOSE_ADD_EXPENSE_MODEL = 'CLOSE_ADD_EXPENSE_MODEL';
